version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Add this line to persist Redis data

volumes:
  postgres_data:
  redis_data: # Add this line to define the volume